version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/www
permissions:
  - object: /home/ec2-user/www
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# hooks:
#   BeforeInstall:
#     - location: scripts/aws_clean_instance.sh
#       timeout: 6000
#       runas: root
#   AfterInstall:
#     - location: scripts/aws_install_os_dependencies.sh
#       timeout: 6000
#       runas: root
#     - location: scripts/aws_install_python_dependencies.sh
#       timeout: 6000
#       runas: ec2-user
#     - location: scripts/aws_migrate.sh
#       timeout: 6000
#       runas: ec2-user
#     - location: scripts/aws_ngnix.sh
#       timeout: 6000
#       runas: ec2-user
#   ApplicationStart:
#     - location: scripts/aws_start_app.sh
#       timeout: 6000
#       runas: ec2-user
#   ApplicationStop:
#     - location: scripts/aws_stop_app.sh
#       timeout: 6000
#       runas: ec2-user
