# Generated by Django 3.1 on 2020-08-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Bid', models.AutoField(primary_key=True, serialize=False)),
                ('Author_name', models.CharField(max_length=50)),
                ('Blog_title', models.CharField(max_length=100)),
                ('Blog_slug', models.CharField(max_length=150)),
                ('Blog_content', models.TextField(max_length=5000)),
                ('Blog_time', models.DateTimeField()),
                ('Blog_image', models.ImageField(default='', upload_to='blog/Images')),
            ],
        ),
    ]
