# Generated by Django 3.1 on 2020-08-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_category',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
