# Generated by Django 3.1 on 2020-08-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_auto_20200809_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_image',
            field=models.ImageField(default='', upload_to='blog/Images'),
        ),
    ]
