# Generated by Django 3.1 on 2020-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Content', models.TextField(max_length=6000)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
